Author: Allen Wang(id: 20008111), Zimeng Fu(id: 20008103)

Configuration:
  language:java
  The function of the Text Editor:

    File(containing New, Open, Save, Print):

      New: Creat a new text editor from the old one.
      Open: Open a local file and read the content with the tezt editor.
      Save: Save the content that written on the text editor.
      Print: Open a Print window that can print the text on the either the text editor or the local text file.

    Search: Search the word or number you want to search, then it'll be selected.

    View: no function

    Manage(containing only exit function):

      Exit: the program stop immediately once you click it.

    About: Show the information of developers.

  Time and Date: There is a label at the right side of manubar that can show the local time.

  Text area: The words written here can wrap automately
             font style: regular script
             font size: 15